apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-reverse-service
  namespace: ci-cd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  echo-reverse-service
  template:
    metadata:
      namespace: ci-cd-test
      labels:
        app:  echo-reverse-service
    spec:
      containers:
        - name:  echo-reverse-service
          image: {{ .Values.werf.image.app }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
