apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-reverse-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  echo-reverse-service
  template:
    metadata:
      labels:
        app:  echo-reverse-service
    spec:
      containers:
        - name:  echo-reverse-service
          image: {{ index  .Values.werf.image "echo-reverse-service" }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
              protocol: TCP
